const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const storage=new Map();
const context=vm.createContext({location:{hostname:'yukohara2501.github.io',origin:'https://yukohara2501.github.io'},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)}});
vm.runInContext(fs.readFileSync(__dirname+'/case-link.js','utf8'),context);
const bridge=context.TeleproCaseLink;
assert.equal(bridge.parse('#/cases/K-2026-027/highlights').id,'K-2026-027');
assert.equal(bridge.parse('#/cases/K-DEMO-020/outcome').view,'outcome');
for(const value of ['#/cases/../highlights','#/cases/<script>/highlights','#/cases/K-2026-027/other','#/cases/%2F/highlights'])assert.equal(bridge.parse(value),null);
assert.equal(bridge.destination('Auto-OP-Record','K-2026-027'),'https://yukohara2501.github.io/Auto-OP-Record/#/cases/K-2026-027/highlights');
bridge.save('A',{outcome:{minutes:'201'}});bridge.save('A',{highlights:{clips:[{start:10,end:20}]}});bridge.save('B',{outcome:{minutes:'55'}});
assert.equal(bridge.merge({id:'A'}).outcome.minutes,'201');
assert.equal(bridge.merge({id:'A'}).highlights.clips[0].start,10);
assert.equal(bridge.merge({id:'B'}).outcome.minutes,'55');
assert.equal(bridge.merge({id:'C'}).outcome,undefined);
bridge.save('A',{outcome:null});assert.equal(bridge.merge({id:'A',outcome:{minutes:'10'}}).outcome,null);
storage.set(bridge.hubKey,JSON.stringify([{id:'A',type:'keio',completed:true,procedure:'Updated name',highlights:{clips:[]}}]));
const catalogue=bridge.catalogue([{id:'A',seconds:14700,procedure:'Seed'}]);
assert.equal(catalogue[0].seconds,14700);assert.equal(catalogue[0].procedure,'Updated name');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
assert.equal((html.match(/id="tp-outcome-form"/g)||[]).length,1);
assert.ok(html.includes('tp-route-error'));
console.log('Case deep-link routing, record-specific merging, and independent highlight/Outcome persistence passed.');
